version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: ecostream-db
    restart: always  # Auto-restarts Postgres if it crashes
    environment:
      - POSTGRES_USER=eco_user
      - POSTGRES_PASSWORD=eco_pass
      - POSTGRES_DB=shipment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ecostream-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  redis:
    image: redis:7.2-alpine
    container_name: ecostream-redis
    restart: always
    ports:
           - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ecostream-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Force Kafka to use less memory so it doesn't crash
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

volumes:
  postgres_data: